name: Linux Polars Pinned Nightly
# polars nightly is pinned to a specific nightly version
# set at https://github.com/pola-rs/polars/blob/main/rust-toolchain.toml

on:
  schedule:
    - cron: "0 */24 * * *"
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5.4.0
      with:
        python-version: '3.12'
    - name: apt-get update Ubuntu, libwayland-dev
      run: |
        sudo apt-get update
        sudo apt-get install libwayland-dev
    - name: Install and Run Redis
      run: |
        sudo apt-get install redis-server
        sudo service redis-server start
    - name: Installing Rust toolchain
      uses: actions-rs/toolchain@v1
      with:
        # set to the pinned nightly version known to work with polars
        toolchain: nightly-2025-03-07
        profile: minimal
        components: rust-src
        target: x86_64-unknown-linux-gnu
        override: true
        default: true
    - name: Run tests
      env:
        RUSTFLAGS: -C target-feature=+sse3,+ssse3,+sse4.1,+sse4.2,+popcnt,+avx,+avx2,+fma,+bmi1,+bmi2,+lzcnt,+pclmulqdq
        # RUSTFLAGS: -C target-cpu=native
      run: cargo test --verbose --locked --features=apply,fetch,foreach,geocode,luau,python,feature_capable,nightly,to,polars,lens
