name: Linux

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

concurrency:
  group: ci-linux-tests-${{ github.ref }}-1
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Maximize build space
      uses: easimon/maximize-build-space@master
      with:
        swap-size-mb: 1024
        remove-dotnet: 'true'
        remove-android: 'true'
        remove-haskell: 'true'
        remove-docker-images: 'true'
    - name: apt-get update Ubuntu, libwayland-dev
      run: |
        sudo apt-get update
        sudo apt-get install libwayland-dev
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5.3.0
      with:
        python-version: '3.12'
    - name: Install and Run Redis
      run: |
        sudo apt-get install redis-server
        sudo service redis-server start
    - name: Update Rust
      run: rustup update
    # - name: Setup Rust-cache
    #   uses: Swatinem/rust-cache@v2
    #   with:
    #     key: qsv-cache
    - name: Run tests
      env:
        RUSTFLAGS: -C target-feature=+sse3,+ssse3,+sse4.1,+sse4.2,+popcnt,+avx,+avx2,+fma,+bmi1,+bmi2,+lzcnt,+pclmulqdq
      run: cargo test --verbose --locked --features=apply,fetch,foreach,geocode,luau,python,feature_capable,lens
